// prev-src/lib/ui/spinner.tsx
import { Loader2Icon } from 'lucide-react'
import { cn } from '~/lib/ui/utils'

function Spinner({ className, ...props }: React.ComponentProps<'svg'>) {
  return (
    <Loader2Icon
      role="status"
      aria-label="Loading"
      className={cn('size-4 animate-spin', className)}
      {...props}
    />
  )
}

export { Spinner }

// app/lib/ui/components/spinner/Spinner.vue
<script setup lang="ts">
import { cn } from '@/lib/ui/utils'
import { Loader2Icon } from 'lucide-vue-next'
import type { HTMLAttributes } from 'vue'

const props = defineProps<{
  class?: HTMLAttributes['class']
}>()
</script>

<template>
  <Loader2Icon
    role="status"
    aria-label="Loading"
    :class="cn('size-4 animate-spin', props.class)" />
</template>
